SELECT 
    A.KODE AS KODE_PROVINSI ,
    A.NAME AS NAMA_PROVINSI,
    B.KODE AS KODE_CITY,
    B.NAME AS NAMA_CITY,
    C.KODE AS KODE_KECAMATAN,
    C.NAME AS NAMA_KECAMATAN,
    D.KODE AS KODE_DESA,
    D.NAME AS NAMA_DESAA
FROM 
(
SELECT * FROM HR.DATA_WILAYAH A
WHERE LENGTH(KODE) = 2 ) A
INNER JOIN
(
SELECT * FROM HR.DATA_WILAYAH B
WHERE LENGTH(KODE) = 5 ) B
ON A.KODE = SUBSTR(B.KODE,1,2)
INNER JOIN
(
SELECT * FROM HR.DATA_WILAYAH C
WHERE LENGTH(KODE) = 8 ) C
ON SUBSTR(B.KODE,1,5) = SUBSTR(C.KODE,1,5)
INNER JOIN
(
SELECT * FROM HR.DATA_WILAYAH D
WHERE LENGTH(KODE) = 13 ) D
ON SUBSTR(C.KODE,1,8) = SUBSTR(D.KODE,1,8)
